#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# The MIT License (MIT)
#
# Copyright (c) 2016-2018 CWT Authors
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# Authors: Petr Hracek <phracek@redhat.com>

import logging
import click


from auto_merger.config import GlobalConfig
from auto_merger.utils import setup_logger
from auto_merger.cli.pr_checker import pr_checker
from auto_merger.cli.merger import merger
logger = logging.getLogger(__name__)


@click.group("auto-merger")
@click.option("-d", "--debug", is_flag=True, help="Enable debug logs")
@click.pass_context
def auto_merger(ctx, debug):
    ctx.obj = GlobalConfig(debug=debug)
    if ctx.obj.debug:
        setup_logger("auto-merger", level=logging.DEBUG)
        logger.debug("Logging set to DEBUG")
    else:
        setup_logger("auto-merger", level=logging.INFO)
        logger.debug("Logging set to INFO")

auto_merger.add_command(pr_checker)
auto_merger.add_command(merger)


if __name__ == "__main__":
    auto_merger(obj={})
